// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetChannels():Promise<Array<main.Channel>>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function LoginWithBrowser(arg1:string):Promise<string>;

export function SelectOutputDirectory():Promise<string>;

export function StartSync(arg1:Array<string>,arg2:string,arg3:Array<string>):Promise<void>;

export function StartSyncURLs(arg1:Array<string>,arg2:string,arg3:Array<string>):Promise<void>;
