// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function LoginWithBrowser(arg1) {
  return window['go']['main']['App']['LoginWithBrowser'](arg1);
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function StartSync(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSync'](arg1, arg2, arg3);
}

export function StartSyncURLs(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSyncURLs'](arg1, arg2, arg3);
}
